spring:
  server:
    connection-timout:
    max-http-header-size: "8192"
    session:
      time-out: 2000
#数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Booktable?&useSSL=false
    username: root
    password: 466204092253x

#jpa配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
#mongo配置
  data:
    mongodb:
      database: bookstore
      uri: mongodb://127.0.0.1:27017
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 466204092
  redis:
    host: 127.0.0.1
    port: 6379
    password: password
    timeout: 0

kafka:
      producer:
        servers: 127.0.0.1:9092
        retries: 0
        linger: 1
        batch:
          size: 4096
        buffer:
          memory: 40960